# Generated by Django 2.2.3 on 2020-11-27 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=2)),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=50)),
                ('nacionalidad', models.CharField(choices=[('--Seleccione una opción--', 'Seleccione una opcion'), ('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('República Dominicana', 'República Dominicana'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('España', 'España'), ('Guinea Ecuatorial', 'Guinea Ecuatorial'), ('Otro', 'Otro')], max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
