# Generated by Django 2.2.3 on 2020-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_auto_20201127_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default=True, max_length=6),
            preserve_default=False,
        ),
    ]
