# Generated by Django 2.2.3 on 2020-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariojoker',
            name='usuario',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
