# Generated by Django 2.2.3 on 2020-11-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_comentariojoker_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodolittle',
            name='usuario',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarioendgame',
            name='usuario',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarioguerra',
            name='usuario',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
