# Generated by Django 2.2.3 on 2020-11-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_auto_20201129_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariojoker',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
